### ISSUE TITLE
Start the wallet with the default active tab set to "details" instead of "transactions"

### ISSUE THREAD

**Issue by Aleoami** [aspectron/kaspa-ng#33]
When there are many transactions on the wallet, it takes it quite some time to "decrypt", the way it's described on the main window.

Or probably estimate the number of transactions in the history, and if it's larger than a certain number, switch to "details" tab, and let the user switch back to "transactions" once at least the balance is visible.

**Comment by aspect** [comment]
Upcoming release introduces pagination to the transaction view, solving this issue.
